### ISSUE TITLE
DOC: How to connect LLMstudio to Azure OpenAI?

### ISSUE THREAD

**Issue by ericthomas1** [TensorOpsAI/LLMstudio#64]
### Issue with current documentation

I can't find how to configure LLMstudio for Azure OpenAI.

### Idea or Request

Please provide docs for this. Thank you.

**Comment by MiNeves00** [comment]
@claudiolemos  can you provide a quick guide on how to configure Azure OpenAI? I know you have demonstrated how to do so for others.

**Comment by ericthomas1** [comment]
I tried adding `"api_version": "2023-05-15"",` to the POST request. Same error.

**Comment by ericthomas1** [comment]
Bump

**Comment by claudiolemos** [comment]
Hey @ericthomas1 sorry. We just fixed this!


1. Run `pip install --upgrade llmstudio`
2. Create a .env on the path you will run LLMstudio

```python
AZURE_API_KEY=""
AZURE_API_ENDPOINT=""
AZURE_API_VERSION=""
```

3. Create a config.yaml file on the path you will run LLMstudio

```yaml
providers:
  azure:
    models:
      YOUR_GPT_DEPLOYMENT_NAME:
        mode: chat
        max_tokens: 32000
        input_token_cost: 0.00006
        output_token_cost: 0.00012
```

4. Now that you've set up your deployment + credentials, run `llmstudio server --ui`

How to test:

**UI**
Proceed to localhost:8000/playground and select your deployment name from the dropdown menu. Send a prompt.

**Python**

from llmstudio import LLM
model = LLM("azure/YOUR_DEPLOYMENT_NAME")
model.chat("tell me a joke")
